### ISSUE TITLE
Query regarding WRFlux for WRF v4.6

### ISSUE THREAD

**Issue by gewitterblitz** [matzegoebel/WRFlux#2]
Hi,

First of all, thank you for making WRFlux open source. I have been running some of my idealized simulations in test mode using WRFlux v1.6.0. I noticed that the recent commits have been about updating WRFlux to match the latest WRF release (v4.6).

Could you please provide an estimate of when the WRF v4.6 compatible version of WRFlux will be released?

Thank you for your help.

**Comment by matzegoebel** [comment]
Hi,
I had to run the test suite first and fix some of the tests. Now I published a new release based on WRF 4.6: https://github.com/matzegoebel/WRFlux/releases/tag/v1.7.0

**Comment by matzegoebel** [comment]
thanks for asking. I had this on my list for a long time, but your request increased the priority. :)

**Comment by milindsharma1** [comment]
Thank you, @matzegoebel. Appreciate your help!
