### ISSUE TITLE
Mismatch in the surface flux?? 

### ISSUE THREAD

**Issue by ngsrinidhi** [matzegoebel/WRFlux#4]
@matzegoebel thanks for making this valuable software opensource! 

I have a rather novice question regarding the average fluxes that are calculated with the model.
If we convert FTZ_SGS_MEAN to W/m2 at the lowest level, shouldn't it match with the HFX values output with the model? (I am not making a full closure of the budget, but rather a visual inspection at this moment), but I do not see the values matching. 
For example, here is a snapshot of the FTZ_SGS_MEAN I get from WRFlux code (at the lowest model level, surface???). The values are low, if I convert this to W/m2 the maximum is around 40-50 W/m2 which is not correct. 
![msrdc_138bbfJlB8](https://github.com/user-attachments/assets/e2e69ff4-7808-4af1-9a9b-d186925dc2f6)

The sensible heatflux (HFX) from wrfout is around 200-300 W/m2.
![msrdc_MSZvq2tQon](https://github.com/user-attachments/assets/45c26a03-a17c-454e-8bea-82c8d40a30ed)

I am trying to calculate 30 minute averages and my namelist has similar settings as the example you have provided. 

I have a feeling that I am missing something fundamental in the way the average is calculated, do you have any idea as to what could be the issue?

**Comment by ngsrinidhi** [comment]
The issue arises when I use nests. The calculations in solve_em.F go awry when I use 3 domains. Basically the averages are reset to zero, before they are output which causes the unusually low fluxes.

**Comment by matzegoebel** [comment]
Thanks @ngsrinidhi for reporting this issue. I've only tested the software for idealized simulations without nesting, so it's quite likely that not everything is done correctly.
Can you upload your namelist file here?

From what you found out, it seems that zero_avgflx is called before the fluxes are output. So maybe the error is in [this line](https://github.com/matzegoebel/WRFlux/blob/afec3b97cd7db57ef2a924bdf8ca71ec5e83194c/dyn_em/solve_em.F#L4795C1-L4795C53
). Directly before, I modified the original code in order to fix a problem if the timestep is not a multiple of 0.01 (commit 83e5b798adf1c23c9c9ff5d8610cd3e0655b5760). Maybe this somehow causes a problem with nests.
You could try to replace:
```fortran
      IF (config_flags%use_adaptive_time_step) THEN
         old_dt=min(old_dt,grid%dt)
         num = INT(old_dt * precision)
         den = precision
      ELSE
         den = config_flags%time_step_fract_den
         num = den*config_flags%time_step + config_flags%time_step_fract_num
      ENDIF
```
with
```fortran
       old_dt=min(old_dt,grid%dt)
       num = INT(old_dt * precision)
       den = precision
```
and see if it works.

It would be amazing if you found out how to fix the problem. Unfortunately, I can't help you much with it, partly because I work in a different field now and don't have the time anymore and partly because I have no idea about nests.

**Comment by ngsrinidhi** [comment]
@matzegoebel Thanks a lot for the reply! 
I already found that the issue is with the same line, but I was making sure the results were good after the fix. I was about to update here, and you also happened to comment!
I compared WRFlux with the WRF-LES diagnostics of Lukasumek and replaced the lines you mentioned above exactly. 

Though the solution is exactly what you mentioned here, the precise issue is slightly different when we use nests. By placing that if construct there the timestep that is taken in the calculation comes from the parent grid. When we use nests, the number of time steps on the child domain does not match (since the time step comes from the parent). Just by replacing it with the appropriate grid_dt the problem disappears. 

I have tested this with multiple nests and the averages look perfect. 

If this fix causes issues with LES output, perhaps it can just be mentioned as a caution somewhere in the documentation, so that people who want it for real cases know about the fix?

**Comment by matzegoebel** [comment]
Thanks for testing. I found a way to make it work for nested runs but also avoid the problem that I found for timesteps like dt = 2/3 s. See commit 314848c438f8d12f12866f8fadd3c2e831dc78a8.
Now the log around the time when the fluxes are output (auxhist24) should look like this:

> Timing for main: time 0001-01-01_00:00:09 on domain   1:    1.36451 elapsed seconds
> solve_em: divide fluxes by density before saving at time 0001-01-01_00:00:09 on domain   1
> Timing for main: time 0001-01-01_00:00:10 on domain   1:  100.11157 elapsed seconds
> Timing for Writing meanout_d01_0001-01-01_00:00:10 for domain        1:    0.36016 elapsed seconds
> solve_em: initializing avgflx at time 0001-01-01_00:00:10 on domain   1
> Timing for main: time 0001-01-01_00:00:10 on domain   1:    1.77127 elapsed seconds

So in the last timestep before saving, the fluxes are divided by the density and after saving zero_avgflx is called to reinitialize the fluxes and tendencies.
Let me know if it works.
